# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_hfun_aqmm <- function(y, X, B, Z, weights, theta_x, v, u, Phi_inv, Sigma_inv, M, N, ni, p, Q, H, s, tau, omega) {
    .Call(`_aqmm_C_hfun_aqmm`, y, X, B, Z, weights, theta_x, v, u, Phi_inv, Sigma_inv, M, N, ni, p, Q, H, s, tau, omega)
}

C_hfunD_aqmm <- function(y, X, B, Z, weights, theta_x, v, u, Phi_inv, Sigma_inv, M, N, ni, p, Q, H, s, tau, omega) {
    .Call(`_aqmm_C_hfunD_aqmm`, y, X, B, Z, weights, theta_x, v, u, Phi_inv, Sigma_inv, M, N, ni, p, Q, H, s, tau, omega)
}

